version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flask-cicd
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application
      timeout: 300
      runas: root


